server:
  port: 8080 # The frontend will ONLY ever talk to Port 8080

spring:
  application:
    name: api-gateway

# Tell the Gateway where to find the Discovery Server Phonebook
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# We will add actual Router Rules here later once we build the Account Service!
