server:
  port: 8080 # The frontend will ONLY ever talk to Port 8080

spring:
  application:
    name: api-gateway
  config:
    import: optional:file:../../.env[.properties]
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - http://localhost:3000
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
      routes:
        - id: account-service-route
          uri: lb://ACCOUNT-SERVICE # lb stands for Load Balancer. It asks the Phonebook (Eureka) for the IP address!
          predicates:
            - Path=/api/accounts/** # Any URL starting with this gets sent to the Account Service
          filters:
            - AuthenticationFilter
        
        - id: auth-service-route
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**

        - id: transaction-service-route
          uri: lb://TRANSACTION-SERVICE
          predicates:
            - Path=/api/transactions/**
          filters:
            - AuthenticationFilter

        - id: openapi-account
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/v3/api-docs/account-service
          filters:
            - RewritePath=/v3/api-docs/account-service, /v3/api-docs

        - id: openapi-auth
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/v3/api-docs/auth-service
          filters:
            - RewritePath=/v3/api-docs/auth-service, /v3/api-docs

        - id: openapi-transaction
          uri: lb://TRANSACTION-SERVICE
          predicates:
            - Path=/v3/api-docs/transaction-service
          filters:
            - RewritePath=/v3/api-docs/transaction-service, /v3/api-docs

springdoc:
  swagger-ui:
    urls:
      - name: Account Service
        url: /v3/api-docs/account-service
      - name: Auth Service
        url: /v3/api-docs/auth-service
      - name: Transaction Service
        url: /v3/api-docs/transaction-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: ${JWT_SECRET}
