package com.nexabank.notificationservice.dto;

import java.math.BigDecimal;

/**
 * Phase 8: Added for Fraud Detection Service
 * Represents a fraud alert generated by the Python Fraud Detection microservice.
 */
public record FraudAlertEvent(
        Long transactionId,
        String clientId,
        String iban,
        BigDecimal amount,
        Double fraudScore,
        Boolean isFraud,
        String reason,
        String timestamp
) {}
